version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_arcadia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: arcadia_zoo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3310:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_arcadia
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ""
      UPLOAD_LIMIT: 100M
    depends_on:
      - mysql

  web:
    build: .
    container_name: web_arcadia
    ports:
      - "8000:80"  # On accède à Symfony via localhost:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

volumes:
  mysql_data:
